### ISSUE TITLE
Move and zoom camera to make points visible

### ISSUE THREAD

**Issue by sbergmair** [fluttercommunity/arcgis_map_sdk#55]
It would be useful if the camera could automatically position itself and zoom in/out so that a list of points is completely visible.

Solution idea:
- Take a list of points
- wrap it into a Geometry
- use following existing functionalty

`ArcgisMapview.setViewpointGeometryAsync(Geometry, padding)`

Android:
https://developers.arcgis.com/kotlin/sample-code/change-viewpoint/

iOS
https://developers.arcgis.com/swift/sample-code/change-viewpoint/

**Comment by JulianBissekkou** [comment]
Closed in #56
