### ISSUE TITLE
Support local files for mobile

### ISSUE THREAD

**Issue by sbergmair** [fluttercommunity/arcgis_map_sdk#57]
There are use cases to provide a local asset as `PicterMarkerSymbol`. This already has been implemented for web.

Solution description:
Use `FlutterPluginRegistrar` (iOS) and `FlutterPluginBinding` (Android) to load the asset from given path (String).
To make this working, only PNG files are supported for the local assets.

**Comment by JulianBissekkou** [comment]
Finished in https://github.com/fluttercommunity/arcgis_map_sdk/pull/58
